[project]
name = "app"
version = "0.1.0"
description = "App"
authors = [
    { name = "Anna van Biemen", email = "annavanbiemen@gmail.com" }
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
app = "app:main"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
